routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });
Auth::routes();

Route::get('/dahsboard', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/dahsboard', 'HomeController@index')->name('home');

// Router web larashop
Route::resource('users', 'UsersController');
//route Categories
Route::get('categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('categories/{id}/delete-permanent', 'CategoryController@deletepermanent')->name('categories.deletepermanent');
Route::resource('categories', 'CategoryController');
//Route Books
Route::delete('books/{id}/delete-permanent','BookController@deletepermanent')->name('books.deletepermanent');
Route::get('books/trash', 'BookController@trash')->name('books.trash');
Route::get('books/{id}/restore', 'BookController@restore')->name('books.restore');
Route::resource('books', 'BookController');
//route data ajax categories
Route::get('ajax/categories/search', 'CategoryController@ajaxSearch');
//route Order
Route::get('orders/personal','OrderController@personalOrder')->name('orders.personal');
Route::put('orders/personal/{order}', 'OrderController@personalOrderUpdate')->name('orders.personal.update');
Route::get('orders/personal/{order}', 'OrderController@personalOrderView')->name('orders.personal.view');
Route::resource('orders', 'OrderController');
//route data ajax book
Route::get('ajax/books/search','BookController@ajaxbooksearch')->name('books.data');
//pagination live serach sorting page orders
Route::get('fetch_book_data','OrderController@fetch_book_data');
Route::get('/province/{id}/cities','OrderController@getCities');
Route::get('/ongkir','OrderController@ongkir')->name('order.ongkir');
//route profile controller
Route::resource('/profile', 'ProfileController')->middleware('auth');
Route::get('/messages/owner','MessageController@contactOwner');
Route::resource('/messages','MessageController');

//route pay controller
Route::post('pay/submit','PayController@paySubmit')->name('pay.submit')->middleware('auth');
Route::post('pay/notif','PayController@payNotif');
Route::post('pay/finish',function(){
    return redirect()->route('orders.personal');
});

//route exportPdf
Route::get('transaction/{id}/details','exportPdf@show')->name('transaction.details')->middleware('auth');
Route::get('cetak/{id}/transaction','exportPdf@cetak')->name('print.transaction')->middleware('auth');
Route::post('reportorders','exportPdf@showReportOrderPdf')->name('report.orders')->middleware('auth');
Route::get('printreportorders','exportPdf@printReportOrderPdf')->name('print.report.orders')->middleware('auth');

//route setting web
Route::get('/','SettingController@sliderHome')->name('index');
Route::get('slider','SettingController@sliderIndex')->name('slider.index');
Route::delete('slider/{id}/delete','SettingController@sliderDestroy')->name('slider.delete');
Route::get('slider/create','SettingController@sliderCreate')->name('slider.create');
Route::post('slider/store','SettingController@sliderStore')->name('slider.store');
Route::get('card/{slug}/categorie','SettingController@cardCategorie')->name('card.categorie');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use softDeletes;
    protected $table = "books";
    protected $primaryKey = "id";
    public function categories()
    {
        return $this->belongsToMany('App\Category');
    }

    public function orders(){
        return $this->belongsToMany('App\Order');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;
use App\Book;
use Illuminate\Support\Facades\DB;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('manage-books');
        $keyword = $request->get('keyword') ? $request->get('keyword') : '';
        $status = $request->get('status');
        if ($status) {
            $book = Book::with('categories')->where("title", "like", "%$keyword%")->where('status', strtoupper($status))->paginate(4);
        } else {
            $book = Book::with('categories')->where("title", "like", "%$keyword%")->paginate(4);
        }
        return view('books.index', ['book'=>$book]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('manage-books');
        return \view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('manage-books');
        \Validator::make($request->all(), [
            "title" => "required|min:5|max:200",
            "description" => "required|min:20|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "required|digits_between:0,10",
            "stock" => "required|digits_between:0,10",
            "cover" => "required"
        ])->validate();
        $new_book = new Book();
        $new_book->title = $request->get('title');
        $new_book->description = $request->get('description');
        $new_book->author = $request->get('author');
        $new_book->publisher = $request->get('publisher');
        $new_book->price = $request->get('price');
        $new_book->stock = $request->get('stock');
        $new_book->status = $request->get('save_action');
        $cover = $request->file('cover');
        if ($cover) {
            $cover_path = $cover->store('book-covers', 'public');
            $new_book->cover = $cover_path;
        }
        $new_book->slug = \Str::slug($request->get('title'));
        $new_book->created_by = \Auth::user()->id;
        $new_book->save();
        $new_book->categories()->attach($request->get('categories'));
        if ($request->get('save_action') == 'PUBLISH') {
            return \redirect()->route('books.create')->with('status', 'Book successfully save and published');
        } elseif ($request->get('save_action') == 'DRAFT') {
            return \redirect()->route('books.create')->with('status', 'Book saved as draft');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('manage-books');
        $book = Book::findOrFail($id);
        return \view('books.edit', ['book'=>$book]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->authorize('manage-books');
        $book = Book::findOrFail($id);
        \Validator::make($request->all(), [
            "title" => "required|min:5|max:200",
            "slug" => [
                "required",
                Rule::unique("books")->ignore($book->slug, "slug")
            ],
            "description" => "required|min:20|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "required|digits_between:0,10",
            "stock" => "required|digits_between:0,10"
        ])->validate();
        $book->title = $request->get('title');
        $book->slug = $request->get('slug');
        $book->description = $request->get('description');
        $book->author = $request->get('author');
        $book->publisher = $request->get('publisher');
        $book->stock = $request->get('stock');
        $book->price = $request->get('price');
        $new_cover = $request->file('cover');
        if ($new_cover) {
            if ($book->cover && file_exists(storage_path('app/public/' .$book->cover))) {
                \Storage::delete('public/'. $book->cover);
            }
            $new_cover_path = $new_cover->store('book-covers', 'public');
            $book->cover = $new_cover_path;
        }
        $book->updated_by = \Auth::user()->id;
        $book->status = $request->get('status');
        $book->save();
        $book->categories()->sync($request->get('categories'));
        return redirect()->route('books.edit', [$book->id])->with('status', 'Book successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('manage-books');
        $book = Book::findOrFail($id);
        $book->deleted_by = \Auth::user()->id;
        $book->save();
        $book->delete();
        return redirect()->route('books.index')->with('status', 'Book moved to trash')->with('type', 'warning');
    }

    public function trash()
    {
        $this->authorize('manage-books');
        $book_trash = Book::onlyTrashed()->paginate(10);
        return view('books.trash', ['book_trash'=>$book_trash]);
    }

    public function restore($id)
    {
        $this->authorize('manage-books');
        $book = Book::withTrashed()->findOrFail($id);
        if ($book->trashed()) {
            $book->deleted_by = null;
            $book->save();
            $book->restore();
        } elseif (!$book->trashed()) {
            return redirect()->route('books.trash')->with('status', 'Book is not in trash');
        }
        return redirect()->route('books.trash')->with('status', 'Book successfully restored')->with('type', 'success');
    }
    public function deletepermanent($id)
    {
        $this->authorize('manage-books');
        $check_book = DB::table('book_order')->where('book_id','=',$id)->count();
        $book = Book::withTrashed()->findOrFail($id);
        if (!$book->trashed()) {
            return redirect()->route('books.index')->with('status', 'can not delete permanent active book')->with('type','warning');
        } elseif($check_book > 0){
            return redirect()->route('books.trash')->with('status', 'cannot delete a book related to the order data')->with('type','warning');
        } elseif ($book->trashed()) {
            if ($book->cover && file_exists(storage_path('app/public/' . $book->cover))) {
                \Storage::delete('public/'.$book->cover);
            }
            $book->categories()->detach();
            $book->forceDelete();
        }
        return \redirect()->route('books.trash')->with('status', 'Category permanently deleted')->with('type', 'danger');
    }
    public function ajaxbooksearch(Request $request){
        $this->authorize('create-orders');
        $keyword = $request->get('q');
        $booksearch = Book::where('title','like',"%$keyword%")->get();
        return $booksearch;
    }
}

resources/views/books/create.blade.php
@extends('layouts.global2')
@section('footer-scripts')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script>
    $('#categories').select2({
    ajax:{
    url:'http://127.0.0.1:8000/ajax/categories/search',
    processResults: function(data){
    return {
    results: data.map(function(item){return{id:item.id,text:item.name}})
    }
    }
    }
    });
</script>
@endsection
@section('title')
Create Book
@endsection
@section('content')
<div class="row">
    <div class="col-md-8">
        @if(session('status'))
        <div class="alert alert-success">
            {{session('status')}}
        </div>
        @endif
        <form action="{{route('books.store')}}" method="POST" class="p-3 rounded shadow bg-white"
            enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="title">Title</label>
                <input class="form-control {{$errors->first('title') ? "is-invalid" : ""}}" value="{{old('title')}}"
                    type="text" name="title" id="title" placeholder="Book Title">
                <small class="form-text text-muted">Title your book</small>
                <div class="invalid-feedback">
                    {{$errors->first('title')}}
                </div>
            </div>
            <div class="custom-file">
                <input type="file" class="custom-file-input {{$errors->first('cover') ? "is-invalid" : ""}}" id="cover"
                    name="cover">
                <label class="custom-file-label" for="cover">Choose a cover image</label>
                <div class="invalid-feedback">
                    {{$errors->first('cover')}}
                </div>
            </div>
            <div class="form-group mt-2">
                <label for="description">Description</label>
                <textarea id="description" class="form-control {{$errors->first('description') ? "is-invalid" : ""}}"
                    rows="2" name="description"
                    placeholder="Give a description about this book">{{old('description')}}</textarea>
                <div class="invalid-feedback">
                    {{$errors->first('description')}}
                </div>
            </div>
            <div class="form-group">
                <label for="categories">Categories</label>
                <select class="form-control" id="categories" multiple name="categories[]">
                </select>
            </div>
            <div class="form-group">
                <label for="stock">Stock</label>
                <input value="{{old('stock') ? old('stock') : "0"}}"
                    class="form-control {{$errors->first('stock') ? "is-invalid" : ""}} " type="number" name="stock"
                    id="stock" min="0">
                <small class="form-text text-muted">Stock your book</small>
                <div class="invalid-feedback">
                    {{$errors->first('stock')}}
                </div>
            </div>
            <div class="form-group">
                <label for="author">Author</label>
                <input value="{{old('author')}}" class="form-control {{$errors->first('author') ? "is-invalid" : ""}}"
                    type="text" name="author" id="author">
                <small class="form-text text-muted">Book author</small>
                <div class="invalid-feedback">
                    {{$errors->first('author')}}
                </div>
            </div>
            <div class="form-group">
                <label for="publisher">Publisher</label>
                <input value="{{old('publisher')}}"
                    class="form-control {{$errors->first('publisher') ? "is-invalid" : ""}}" type="text"
                    name="publisher" id="publisher">
                <small class="form-text text-muted">Book publisher</small>
                <div class="invalid-feedback">
                    {{$errors->first('publisher')}}
                </div>
            </div>
            <div class="form-group">
                <label for="price">Price</label>
                <input value="{{old('price') ? old('price') : "0" }}"
                    class="form-control {{$errors->first('price') ? "is-invalid" : ""}}" type="number" name="price"
                    id="price" min="0">
                <small class="form-text text-muted">Book price</small>
                <div class="invalid-feedback">
                    {{$errors->first('price')}}
                </div>
            </div>
            <button class="btn btn-primary" name="save_action" value="PUBLISH">Publish</button>
            <button class="btn btn-secondary" name="save_action" value="DRAFT">Save as draft</button>
        </form>
    </div>
</div>
@endsection

resources/views/books/edit.blade.php
@extends('layouts.global2')
@section('footer-scripts')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-
rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-
rc.0/js/select2.min.js"></script>
<script>
    $('#categories').select2({
        ajax: {
            url: 'http://127.0.0.1:8000/ajax/categories/search',
            processResults: function(data){
                return {
                    results: data.map(function(item){return {id: item.id, text:item.name} })
            }
        }
    }
});
var categories = {!! $book->categories !!}
    categories.forEach(function(category){
        var option = new Option(category.name, category.id, true, true);
        $('#categories').append(option).trigger('change');
    });
</script>
@endsection
@section('title')
Edit Book
@endsection
@section('content')
<div class="row">
    <div class="col-md-8">
        @if(session('status'))
        <div class="alert alert-success">
            {{session('status')}}
        </div>
        @endif
        <form action="{{route('books.update',[$book->id])}}" method="post" class=" bg-white p-3 rounded shadow"
            enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="_method" value="PUT">
            <div class="form-group">
                <label for="title">Title</label>
                <input value="{{old('title') ? old('title') : $book->title}}"
                    class="form-control {{$errors->first('title') ? "is-invalid" : ""}}" type="text" name="title"
                    id="title" placeholder="Book Titile">
                <small class="form-text text-muted">Title your book</small>
                <div class="invalid-feedback">
                    {{$errors->first('title')}}
                </div>
            </div>
            <label for="cover">Current Image</label><br>
            @if ($book->cover)
            <img class="mb-2" src="{{asset('storage/'.$book->cover)}}" alt="" width="90px">
            @endif
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="cover" name="cover">
                <label class="custom-file-label" for="cover">Choose a cover image</label>
                <small class="text-muted">Kosongkan jika tidak ingin merubah cover</small>
            </div>
            <div class="form-group mt-2">
                <label for="slug">Slug</label>
                <input value="{{old('slug') ? old('slug') : $book->slug}}"
                    class="form-control {{$errors->first('slug') ? "is-invalid" : ""}}" type="text" name="slug"
                    id="slug" placeholder="Enter e slug">
                <div class="invalid-feedback">
                    {{$errors->first('slug')}}
                </div>
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <textarea id="description" class="form-control {{$errors->first('description') ? "is-invalid" : ""}}"
                    rows="2"
                    name="description">{{old('description') ? old('description') : $book->description}}</textarea>
                <div class="invalid-feedback">
                    {{$errors->first('description')}}
                </div>
            </div>
            <div class="form-group">
                <label for="categories">Categories</label>
                <select class="form-control" id="categories" multiple name="categories[]">
                </select>
            </div>
            <div class="form-group">
                <label for="stock">Stock</label>
                <input value="{{old('stock') ? old('stock') : $book->stock}}"
                    class="form-control {{$errors->first('stock') ? "is-invalid" : ""}}" type="number" name="stock"
                    id="stock" min="0">
                <small class="form-text text-muted">Stock your book</small>
                <div class="invalid-feedback">
                    {{$errors->first('stock')}}
                </div>
            </div>
            <div class="form-group">
                <label for="author">Author</label>
                <input value="{{old('author') ? old('author') : $book->author}}"
                    class="form-control {{$errors->first('author') ? "is-invalid" : ""}}" type="text" name="author"
                    id="author">
                <small class="form-text text-muted">Author yout book</small>
                <div class="invalid-feedback">
                    {{$errors->first('author')}}
                </div>
            </div>
            <div class="form-group">
                <label for="publisher">Publisher</label>
                <input value="{{old('publisher') ? old('publisher') : $book->publisher}}"
                    class="form-control {{$errors->first('publisher') ? "is-invalid" : ""}}" type="text"
                    name="publisher" id="publisher">
                <small class="form-text text-muted">Publisher your book</small>
                <div class="invalid-feedback">
                    {{$errors->first('publisher')}}
                </div>
            </div>
            <div class="form-group">
                <label for="price">Price</label>
                <input value="{{old('price') ? old('price') : $book->price}}"
                    class="form-control {{$errors->first('price') ? "is-invalid" : ""}}" type="number" name="price"
                    id="price" min="0">
                <small class="form-text text-muted">Price your book</small>
                <div class="invalid-feedback">
                    {{$errors->first('price')}}
                </div>
            </div>
            <div class="form-group">
                <label for="status">Example select</label>
                <select class="form-control" id="status" name="status">
                    <option {{$book->status == 'PUBLISH' ? 'selected':''}} value="PUBLISH">PUBLISH</option>
                    <option {{$book->status == 'DRAFT' ? 'selected':''}} value="DRAFT">DRAFT</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/books/index.blade.php
@extends('layouts.global2')
@section('title')
All Book
@endsection
@section('content')
<div class="row">
    <div class="col-md-6 mb-2 mb-lg-auto mb-xl-auto mb-md-auto">
        <form action="{{route('books.index')}}">
            <div class="input-group">
                <input name="keyword" type="text" value="{{Request::get('keyword')}}" class="form-control"
                    placeholder="Filter by title">
                <div class="input-group-append">
                    <input type="submit" value="Filter" class="btn btn-primary">
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <ul class="nav nav-pills float-right">
            <li class="nav-item">
                <a class="nav-link {{Request::get('status') == NULL && Request::path() == 'books' ? 'active' : ''}}"
                    href="{{route('books.index')}}">All</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::get('status') == 'publish' ? 'active' : '' }}"
                    href="{{route('books.index', ['status' => 'publish'])}}">Publish</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::get('status') == 'draft' ? 'active' : '' }}"
                    href="{{route('books.index', ['status' => 'draft'])}}">Draft</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::path() == 'books/trash' ? 'active' : ''}}"
                    href="{{route('books.trash')}}">Trash</a>
            </li>
        </ul>
    </div>
</div>
<hr class="my-3">
<div class="row">
    <div class="col-md-12">
        @if(session('status'))
        <div class="alert alert-{{session('type')}}">
            {{session('status')}}
        </div>
        @endif
    </div>
    <div class="col-md-12 overflow-x-y-75">
        <div class="row mb-3">
            <div class="col-md-12 text-right">
                <a href="{{route('books.create')}}" class="btn btn-primary">Create book</a>
            </div>
        </div>
        <div class=" table-responsive-md">
            <table class="table table-bordered table-hover">
                <thead class=" thead-dark">
                    <tr>
                        <th scope="col">Cover</th>
                        <th scope="col">Title</th>
                        <th scope="col">Author</th>
                        <th scope="col">Status</th>
                        <th scope="col">Categories</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Price</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($book as $all_book)
                    <tr>
                        @if($all_book->cover)
                        <td>
                            <img src="{{asset('storage/'.$all_book->cover)}}" alt="" width="96">
                        </td>
                        @endif
                        <td>{{$all_book->title}}</td>
                        <td>{{$all_book->author}}</td>
                        <td>
                            @if ($all_book->status == "DRAFT")
                            <span class="badge bg-dark text-white">{{$all_book->status}}</span>
                            @elseif($all_book->status == "PUBLISH")
                            <span class="badge bg-success text-white">{{$all_book->status}} </span>
                            @endif
                        </td>
                        <td>
                            <ul class="pl-2">
                                @foreach ($all_book->categories as $categories)
                                <li>{{$categories->name}}</li>
                                @endforeach
                            </ul>
                        </td>
                        <td>{{$all_book->stock}}</td>
                        <td>{{$all_book->price}}</td>
                        <td>
                            <a class="btn btn-info btn-sm" href="{{route('books.edit',[$all_book->id])}}"><span
                                    class="oi oi-pencil text-white"></span></a>
                            <form action="{{route('books.destroy',[$all_book->id])}}" class=" d-inline" method="POST"
                                onsubmit="return confirm('Move category to trash?')">
                                @csrf
                                <input type="hidden" name="_method" value="DELETE">
                                <button type="submit" class="btn btn-sm btn-danger"><span
                                        class="fa fa-trash fa-lg"></span></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan=10>
                            {{$book->appends(Request::all())->links()}}
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection