routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });
Auth::routes();

Route::get('/dahsboard', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/dahsboard', 'HomeController@index')->name('home');

// Router web larashop
Route::resource('users', 'UsersController');
//route Categories
Route::get('categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('categories/{id}/delete-permanent', 'CategoryController@deletepermanent')->name('categories.deletepermanent');
Route::resource('categories', 'CategoryController');
//Route Books
Route::delete('books/{id}/delete-permanent','BookController@deletepermanent')->name('books.deletepermanent');
Route::get('books/trash', 'BookController@trash')->name('books.trash');
Route::get('books/{id}/restore', 'BookController@restore')->name('books.restore');
Route::resource('books', 'BookController');
//route data ajax categories
Route::get('ajax/categories/search', 'CategoryController@ajaxSearch');
//route Order
Route::get('orders/personal','OrderController@personalOrder')->name('orders.personal');
Route::put('orders/personal/{order}', 'OrderController@personalOrderUpdate')->name('orders.personal.update');
Route::get('orders/personal/{order}', 'OrderController@personalOrderView')->name('orders.personal.view');
Route::resource('orders', 'OrderController');
//route data ajax book
Route::get('ajax/books/search','BookController@ajaxbooksearch')->name('books.data');
//pagination live serach sorting page orders
Route::get('fetch_book_data','OrderController@fetch_book_data');
Route::get('/province/{id}/cities','OrderController@getCities');
Route::get('/ongkir','OrderController@ongkir')->name('order.ongkir');
//route profile controller
Route::resource('/profile', 'ProfileController')->middleware('auth');
Route::get('/messages/owner','MessageController@contactOwner');
Route::resource('/messages','MessageController');

//route pay controller
Route::post('pay/submit','PayController@paySubmit')->name('pay.submit')->middleware('auth');
Route::post('pay/notif','PayController@payNotif');
Route::post('pay/finish',function(){
    return redirect()->route('orders.personal');
});

//route exportPdf
Route::get('transaction/{id}/details','exportPdf@show')->name('transaction.details')->middleware('auth');
Route::get('cetak/{id}/transaction','exportPdf@cetak')->name('print.transaction')->middleware('auth');
Route::post('reportorders','exportPdf@showReportOrderPdf')->name('report.orders')->middleware('auth');
Route::get('printreportorders','exportPdf@printReportOrderPdf')->name('print.report.orders')->middleware('auth');

//route setting web
Route::get('/','SettingController@sliderHome')->name('index');
Route::get('slider','SettingController@sliderIndex')->name('slider.index');
Route::delete('slider/{id}/delete','SettingController@sliderDestroy')->name('slider.delete');
Route::get('slider/create','SettingController@sliderCreate')->name('slider.create');
Route::post('slider/store','SettingController@sliderStore')->name('slider.store');
Route::get('card/{slug}/categorie','SettingController@cardCategorie')->name('card.categorie');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<!--[if IE 9]> <html class="ie9 no-js" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BookStore @yield("title")</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css"
        integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link rel="stylesheet" href="{{asset('polished/iconic/css/open-iconic-bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <style>
        .navbar {
            padding: 0.5rem 1rem;
        }

        .rounded-login {
            border-radius: 3%;
        }

        .form-control,
        .input-group-text {
            border: none;
            box-shadow: none;
            border-bottom: 1px solid #ced4da;
            border-radius: 0px;
        }

        .form-control:focus,
        .is-invalid:focus {
            box-shadow: none !important;
            border-color: orange !important;
        }

        .border-warning,
        .is-invalid {
            border-color: orange !important;
        }

        .card-header-circle {
            background-color: #f8b739;
            height: 100px;
            width: 100px
        }

        .card-icon {
            margin-top: 20%;
            width: 100%;
            height: 100%;
            font-size: 60px;
            color: white;
            align-items: center;
            text-align: center;
        }

        .border-bottom {
            border-bottom: 5px solid #dee2e6 !important;
        }

        .border-warning {
            border-color: orange !important;
        }

        .color-orange:hover {
            background-color: orange;
        }

        .color-orange {
            color: orange;
            border: 1px solid orange;
        }

        .dropdown-item:hover {
            background-color: orange;
        }

        .img-carousel {
            height: 400px !important;
        }

        .orange {
            background-color: orange !important;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark justify-content-between border-bottom border-warning">
        <a class="navbar-brand ml-lg-5" href="{{ route('index') }}">BookStore</a>
        {{-- <input class=" form-control d-none d-md-block w-50 ml-3 mr-2" type="text" placeholder="Search" aria-label="Search"> --}}
        <button class="btn btn-link d-block d-lg-none d-md-none" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {{-- <div class="ml-5 collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item d-xl-block d-lg-block d-md-none d-sm-none ml-5" style="width:100% !important; ">
                    <div class="input-group mt-1 ml-5">
                        <input type="text" class="form-control ml-5" placeholder="Search Book"
                            aria-describedby="basic-addon2" style="widows: 100px;dth: ">
                        <div class="input-group-append">
                            <button type="submit" class="btn color-orange btn-outline-secondary mr-lg-5"
                                type="button">Search</button>
                        </div>
                    </div>
                </li>
                <li class="nav-item dropdown d-xl-block d-lg-block d-md-none d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categories &MediumSpace;
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
        </div> --}}
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ">
                    <form action="{{ route('index') }}" method="get">
                        <div class="input-group mt-1">
                            <input type="text" class="form-control ml-3" placeholder="Search Book"
                                aria-describedby="basic-addon2" name="keyword" value="{{Request::get('keyword')}}">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-outline-secondary color-orange"
                                    type="button">Search</button>
                            </div>
                        </div>
                    </form>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categories &MediumSpace;
                    </a>
                    <div class="dropdown-menu bg-dark border border-warning" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item text-white" href="http://127.0.0.1:8000/card/php/categorie">PHP</a>
                        <a class="dropdown-item text-white" href="http://127.0.0.1:8000/card/mysql/categorie">MYSQL</a>
                        <a class="dropdown-item text-white" href="http://127.0.0.1:8000/card/javascript/categorie">Javascript</a>
                        <a class="dropdown-item text-white" href="http://127.0.0.1:8000/card/jquery/categorie">Jquery</a>
                        <a class="dropdown-item text-white" href="http://127.0.0.1:8000/card/vue-js/categorie">VUE JS</a>
                        <a class="dropdown-item text-white" href="http://127.0.0.1:8000/card/react-js/categorie">React js</a>
                        <a class="dropdown-item text-white" href="{{ route('index') }}">Another Category</a>
                    </div>
                </li>
                @if (Auth::user())
                <li class="nav-item mr-lg-1 mr-md-1">
                    <a class="nav-link" href="{{route('home')}}"><i class="fas fa-home"></i>
                        Dashboard</a>
                </li>
                <li class="nav-item">
                    <form action="{{route("logout")}}" method="POST" class="form-inline">
                        @csrf
                        <button class="pl-0 btn btn-lg btn-dark text-white-50"><i class="fas fa-sign-out-alt"></i> Sign
                            Out</button>
                    </form>
                </li>
                @else
                <li class="nav-item">
                    <a class="nav-link active text-white" href="{{route('login')}}"><i class="fas fa-sign-in-alt"></i>
                        Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white-50" href="{{route('register')}}"><i class="fas fa-sign-in-alt"></i>
                        Register</a>
                </li>
                @endif
            </ul>
        </div>
    </nav>
    <section style="min-height: 100vh">
        <div class="container-fluid h-100 p-0">
            <div style="min-height: 100%" class="">
                <div class="col-lg-12 col-md-12 p-4">
                    @yield("content")
                </div>
            </div>
        </div>
        <div class="container-fluid">
            @yield('home-content')
        </div>
    </section>
    <!-- Footer -->
    <footer class="font-small bg-dark text-white mt-3">
        <div class="text-center py-3 orange">© 2020 Copyright: Arya Irama Wahono
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous">
    </script>
    <script>
        $(':input').on('focusin',function(){
            let id = this.id;
            if(id.length == 0){
                true;
            } else if (id.length > 0){
                $(`#${id}`).addClass('border-warning')
            }
        });
        $(':input').on('focusout',function(){
            let id = this.id;
            if(id.length == 0){
                true;
            } else if (id.length > 0){
                $(`#${id}`).removeClass('border-warning')
            }
        });
    </script>
    @yield("script")
</body>

</html>

resources/views/layouts/global.blade.php
<!DOCTYPE html>
<!--[if IE 9]> <html class="ie9 no-js" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Larashop @yield("title")</title>
    <link rel="stylesheet" href="{{asset('polished/polished.min.css')}}">
    <link rel="stylesheet" href="{{asset('polished/iconic/css/open-iconic-bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('font-awesome-4.7.0/css/font-awesome.min.css')}} ">
    <link rel="stylesheet" href="{{asset('css/style.css')}} ">
    <style>
        .grid-highlight {
            padding-top: 1rem;
            padding-bottom: 1rem;
            background-color: #5c6ac4;
            border: 1px solid #202e78;
            color: #fff;
        }

        hr {
            margin: 6rem 0;
        }

        hr+.display-3,
        hr+.display-2+.display-3 {
            margin-bottom: 2rem;
        }
    </style>
    <script type="text/javascript">
        document.documentElement.className =
document.documentElement.className.replace('no-js', 'js') +
(document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure", "1.1") ? ' svg' : ' no-svg');
    </script>
</head>

<body>
    <nav class="navbar navbar-expand p-0">
        <a class="navbar-brand text-center col-xs-12 col-md-3 col-lg-2 mr-0" href="/"> Larashop </a>
        <button class="btn btn-link d-block d-md-none" data-toggle="collapse" data-target="#sidebar-nav" role="button">
            <span class="oi oi-menu"></span>
        </button>

        <input class="border-dark bg-primary-darkest form-control d-none d-md-block w-50 ml-3 mr-2" type="text"
            placeholder="Search" aria-label="Search">
        <div class="dropdown d-none d-md-block">
            @if(\Auth::user())
            <button class="btn btn-link btn-link-primary dropdown-toggle" id="navbar-dropdown" data-toggle="dropdown">
                {{Auth::user()->name}}
            </button>
            @endif
            <div class="dropdown-menu dropdown-menu-right" id="navbardropdown">
                <a href="#" class="dropdown-item">Profile</a>
                <a href="#" class="dropdown-item">Setting</a>
                <div class="dropdown-divider"></div>
                <li>
                    <form action="{{route("logout")}}" method="POST">
                        @csrf
                        <button class="dropdown-item" style="cursor:pointer">Sign Out</button>
                    </form>
                </li>
            </div>
        </div>
    </nav>
    <div class="container-fluid h-100 p-0">
        <div style="min-height: 100%" class="flex-row d-flex align-items-stretch m-0">
            <div class="polished-sidebar bg-light col-12 col-md-3 col-lg-2 p-0 collapse d-md-inline" id="sidebar-nav">
                <ul class="polished-sidebar-menu ml-0 pt-4 p-0 d-md-block">
                    <input class="border-dark form-control d-block d-md-none mb-4" type="text" placeholder="Search"
                        aria-label="Search" />
                    <li><a href="/"><span class="oi oi-home"></span>Home</a></li>
                    @can('create-orders')
                    <li><a href="{{route('orders.create')}}"><span class="fa fa-plus"></span> Create Order</a></li>
                    @endcan
                    @can('manage-users')
                    <li><a href="{{ route('users.index') }} "><span class="oi oi-people"></span>Manage User</a></li>
                    @endcan
                    @can('manage-categories')
                    <li><a href="{{ route('categories.index') }} "><span class="oi oi-tag"></span>Manage Category</a>
                    </li>
                    @endcan
                    @can('manage-books')
                    <li><a href="{{ route('books.index') }} "><span class="oi oi-book"></span>Manage Book</a></li>
                    @endcan
                    @can('manage-orders')
                    <li><a href="{{ route('orders.index') }} "><span class="oi oi-inbox"></span>Manage Order</a></li>
                    @endcan
                    <div class="d-block d-md-none">
                        <div class="dropdown-divider"></div>
                        <li><a href="#"> Profile</a></li>
                        <li><a href="#"> Setting</a></li>
                        <li>
                            <form action="{{route("logout")}}" method="POST">
                                @csrf
                                <button class="dropdown-item" style="cursor:pointer">Sign Out</button>
                            </form>
                        </li>
                    </div>
                </ul>
                <div class="pl-3 d-none d-md-block position-fixed" style="bottom: 0px">
                    <span class="oi oi-cog"></span> Setting
                </div>
            </div>
            <div class="col-lg-10 col-md-9 p-4">
                <div class="row ">
                    <div class="col-md-12 pl-3 pt-2">
                        <div class="pl-3">
                            <h3>@yield("pageTitle")</h3>
                            <br />
                        </div>
                    </div>
                </div> @yield("content")
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous">
    </script>
    @yield('footer-scripts')
</body>

</html>

resources/views/layouts/global2.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BookStore @yield("title")</title>
    {{-- Fontawesome Icon --}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css"
        integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">
    {{-- Fontawesome Icon --}}
    {{-- Bootstrap CDN --}}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {{-- Bootstrap CDN --}}
    {{-- Polished Icon --}}
    <link rel="stylesheet" href="{{asset('polished/iconic/css/open-iconic-bootstrap.min.css')}}">
    {{-- Polished Icon --}}
    {{-- Sidebar --}}
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    {{-- Sidebar --}}
</head>

<body>
    <div class="wrapper d-flex align-items-stretch">
        @if (Auth::user())
        <nav id="sidebar">
            <div class="p-4">
                @if (\Auth::user())
                <a href="#" class="img logo rounded-circle mb-5"
                    style="background-image: url(/storage/{{Auth::user()->avatar}});background-size: cover;background-position: center center;"></a>
                @endif
                <ul class="list-unstyled components mb-5">
                    <li class="">
                        <a href="{{ route('home') }}"><span class="oi oi-home"></span> Home</a>
                    </li>
                    @can('create-messages')
                    <li><a href="{{route('messages.index')}}"><span class="fas fa-comment-alt"></span> Messages</a></li>
                    @endcan
                    @can('create-orders')
                    <li><a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false"
                            class="dropdown-toggle"><span class="oi oi-inbox"></span> Order</a>
                        <ul class="collapse list-unstyled" id="homeSubmenu">
                            @can('create-orders')
                            <li><a href="{{route('index')}}"><span class="fa fa-plus"></span> Create Order</a>
                            </li>
                            <li><a href="{{route('orders.personal')}}"><span class="fas fa-dolly-flatbed"></span> My Order</a>
                            </li>
                            @endcan
                            @can('manage-orders')
                            <li><a href="{{ route('orders.index') }} "><span class="oi oi-inbox"></span> Manage
                                    Order</a></li>
                            @endcan
                        </ul>
                    </li>
                    @endcan
                    @can('manage-users')
                    <li><a href="{{ route('users.index') }} "><span class="oi oi-people"></span> Manage User</a></li>
                    @endcan
                    @can('manage-categories')
                    <li><a href="{{ route('categories.index')}} "><span class="oi oi-tag"></span> Manage Category</a>
                    </li>
                    @endcan
                    @can('manage-books')
                    <li><a href="{{ route('books.index') }} "><span class="oi oi-book"></span> Manage Book</a></li>
                    @endcan
                    @can('manage-orders')
                    <li><a href="#setting" data-toggle="collapse" aria-expanded="false"
                        class="dropdown-toggle"><span class="fas fa-cog"></span> Setting</a>
                    <ul class="collapse list-unstyled" id="setting">
                        <li><a href="{{ route('slider.index') }}"><span class="fas fa-sliders-h"></span> Slider</a></li>
                    </ul>
                </li>
                    @endcan
                </ul>
                <div class="footer"></div>
            </div>
        </nav>
        @endif
        <!-- Page Content  -->
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    @if (\Auth::user())
                    <button type="button" id="sidebarCollapse" class="btn btn-primary">
                        <i class="fa fa-bars"></i>
                        <span class="sr-only">Toggle Menu</span>
                    </button>
                    @endif
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fa fa-bars"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            @if (Auth::user())
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink"
                                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img src="/storage/{{Auth::user()->avatar}}" class="rounded-circle img-icon-profile"
                                        alt="">
                                    {{Auth::user()->name}}&MediumSpace;&MediumSpace;
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="#" onclick="editProfile({{Auth::user()->id}})"><i
                                            class="far fa-user"></i> Profile</a>
                                    <form action="{{route("logout")}}" method="POST" class="form-inline">
                                        @csrf
                                        <button class="dropdown-item" style="cursor:pointer"><i
                                                class="fas fa-sign-out-alt"></i> Sign Out</button>
                                    </form>
                                </div>
                            </li>
                            @else
                            <li class="nav-item">
                            <a class="nav-link active" href="{{route('login')}}"><i class="fas fa-sign-in-alt"></i> Login</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="{{route('register')}}"><i class="fas fa-sign-in-alt"></i> Register</a>
                            </li>
                            @endif
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container-fluid mb-5">
                @yield("content")
            </div>
            @auth
            @include('modal.profile_modal')
            @endauth
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/jquery.validate.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/additional-methods.js"></script>
    <script src="{{asset('sidebar/js/main.js')}}"></script>
    <script src="{{asset('js/profile.js')}}"></script>
    @yield('footer-scripts')
</body>

</html>